# Generated by Django 3.0.8 on 2021-12-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frejun_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={},
        ),
    ]
