# Generated by Django 3.0.8 on 2021-12-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frejun_api_app', '0002_auto_20211225_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frejun_api_app.Account'),
        ),
    ]
